name: auto android play publish 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install all packages
      run: npm install
    - name: Build app
      run: tsc
    - name: test test cases
      run: npm test
      env:
          client_email: ${{ secrets.client_email }}
          private_key: ${{ secrets.private_key }}
          releaseFilePath: "release/app.apk"
          releaseNotes: "this is the cool release"
          track: internal
    - name: run code
      run: npm start
      env:
          client_email: ${{ secrets.client_email }}
          private_key: ${{ secrets.private_key }}
          releaseFilePath: "release/app.apk"
          releaseNotes: "this is the cool release"
          track: internal

